---
title: "springer"
output: html_notebook
---
```{r Erstellung Netzwerk}
library("igraph")
library("igraphdata")
# Einlesen der Edgelist aus github link: beachte den Separator ","
edges <- read.csv("https://raw.githubusercontent.com/AninaWaelti/Springer-Netzwerk/master/Codebuch%20Springer%20-%20Edgelist.csv", header=T, as.is=T, sep = ",")
# Einlesen der Nodelist
nodes <- read.csv("https://raw.githubusercontent.com/AninaWaelti/Springer-Netzwerk/master/Codebuch%20Springer%20-%20Nodelist.csv", header=T, as.is=T, sep = ",")
# ????berpr????fen der Daten
head(edges)
head(nodes)
# wandelt die Edgelist als Matrix um.
edgematrix <-as.matrix(edges)
# ?graph_from_data_frame (erl????utert den Befehl genauer)
# erstellt ein igraph-objekt aus der Fusion von Edge- und Nodelist
springer <- graph_from_data_frame(d=edgematrix, vertices=nodes, directed=T)
# das igraph-Objekt heisst jetzt "s" (f????r springer) und ist ein gerichtetes Netzwerk.
springer
```

```{r Visualisierung Farben}
V(springer)[(V(springer)$type==1)]$shape<-"circle"
V(springer)[(V(springer)$type==1)]$color<-"pink"
V(springer)[(V(springer)$type==2)]$shape<-"square"
V(springer)[(V(springer)$type==2)]$color<-"lightblue"
V(springer)[(V(springer)$media==1)]$color<-"yellow"
V(springer)[(V(springer)$media==3)]$color<-"red"
```

```{r Kanten f??rben}
list.edge.attributes(springer)
edge.attributes(springer)$time

springer
V(springer)$label <- V(springer)$name_2

coords<- layout_with_kk(springer)*0.175
plot(springer,
     edge.arrow.size=.3,
     vertex.size=5,
     layout = coords,
     rescale = FALSE,
     ylim = c(-2.0, 1.3), 
     xlim = c(-1.6, 1.6), 
     asp = 0,
     main="Axel Springer Netzwerk")
```
```{r}
# deleting non-moonwalking vertices


# Wow, that looks quite nice. We will handle the finetuning of the visualization later. But... you said there were 12 men on the moon with 6 lunar missions? Why are there so many edges included? As far as I know, no man walked the moon twice?


media<-delete_vertices(springer, V(springer)[media < 3])
media
mediad<-degree(media, mode="in")
plot(media,
     layout = layout_with_kk,
     vertex.size=mediad*2, # defines the size of the node by degree,
     vertex.label.color="black",
     vertex.label.font=1,
     vertex.label.cex=.75,
     vertex.label.dist=1,
     edge.arrow.size=.3,
     vertex.size=7,
     main = "Unternehmen an denen Springer beteiligt ist")
```

```{r Akteursma??e}
degree(springer)
components(springer)
diameter(springer) 
edge_density(springer)
mean_distance(springer)
cluster_walktrap(springer)
triad.census(springer)
```

```{r ego Netzwerk erstellen, Methode 1}

vFriede <- subgraph <- make_ego_graph(springer, order=1, c("Friede Springer"))
plot(vFriede[[1]], edge.arrow.size=.1,vertex.size=5,)

vDoepfner <- subgraph <- make_ego_graph(springer, order=1, c("Dr. Mathias D??pfner"))
plot(vDoepfner[[1]], edge.arrow.size=.1, vertex.size=5,)
```

```{r Methode 2}
t1 <- subgraph.edges(springer, E(springer)[time == " 1"])
t1
plot(t1, edge.arrow.size=.2, vertex.size=5, main="0-4 Jahre im Unternehmen")

t2 <- subgraph.edges(springer, E(springer)[time == " 2"])
t2
plot(t2, edge.arrow.size=.2, vertex.size=5, main="5-10 Jahre im Unternehmen")

t3 <- subgraph.edges(springer, E(springer)[time == " 3"])
t3
plot(t3, edge.arrow.size=.2, vertex.size=5, main="11-20 Jahre im Unternehmen")

t4 <- subgraph.edges(springer, E(springer)[time == " 4"])
t4
plot(t4, edge.arrow.size=.2, vertex.size=5, main="Laenger als 21 Jahre im Unternehmen")

to1 <- subgraph.edges(springer, E(springer)[topicality == " 1"])
to1
plot(to1, edge.arrow.size=.2, vertex.size=5, main="Aktuell")
```
```{r}

t1 <- subgraph.edges(springer, E(springer)[time == " 2"])
t1
plot(t1, edge.arrow.size=.2, main="5-10 Jahre")

t2 <- subgraph.edges(springer, E(springer)[time == " 4"])
t2
plot(t2, edge.arrow.size=.2, main=" 21 und laenger")

```


```{r Cluster erstellen}
gc <- cluster_walktrap(springer)
modularity(gc)
membership(gc)
plot(gc, springer, edge.arrow.size=.2)

```
```{r}
# Inl??ndische Beziehungen 

l1 <- subgraph.edges(springer, E(springer)[location == " 1"])
l1
coords<- layout_with_kk(l1)*0.155
plot(
  l1,
  edge.arrow.size=.2,
  vertex.size=3.5,
  layout = coords,
  rescale = FALSE,
     ylim = c(-1.8, 1.2), 
     xlim = c(-1.0, 1.3), 
     asp = 0,
  main="Inlaendische Beziehungen"
  )

```
```{r}
# Ausl??ndische Beziehungen 


l2 <- subgraph.edges(springer, E(springer)[location == " 2"])
l2
coords<- layout_with_kk(l2)*0.09
plot(
  l2,
  vertex.size=5,
  edge.arrow.size=.2,
  layout = coords,
  rescale = FALSE,
     ylim = c(-1.2, 1.0), 
     xlim = c(-0.7, 1.0), 
     asp = 0,
  main="Auslaendische Beziehungen"
  )


```

```{r}

par(mfrow=c(3,3), mar=c(0,0,2,2))

# Inl??ndische Beziehungen und ausl??ndische Beziehungen im Vergleich

l1 <- subgraph.edges(springer, E(springer)[location == " 1"])
l1
plot(l1, edge.arrow.size=.2, vertex.size=5, main="Inlaendische Beziehungen")

l2 <- subgraph.edges(springer, E(springer)[location == " 2"])
l2
plot(l2, edge.arrow.size=.2, vertex.size=5,main=" Auslaendische Beziehungen")
```


```{r Betweenes Werte berechnen}
# Wer ??bernimmt eine Schl??sselrolle im Netzwerk als Broker?

bs <- betweenness(springer, v = V(springer),
                  directed = TRUE,
                  weights = NULL,
                  nobigint = TRUE,
                  normalized = TRUE)
bs

plot(springer,
     vertex.label=NA,
     vertex.size=bs*100,
     edge.arrow.size=.2,
     main="Verteilung Betweenness im Netzwerk")
delete.vertices(springer, V(springer)<2) 
               
```

```{r ID'S anzeigen}

springer
V(springer)$label <- V(springer)$id
plot(springer)
```

